export const cloudList = [
  { value: 'JavaScript', count: 3 },
  { value: 'CSS4', count: 2 },
  { value: 'HTML6', count: 2 },
  { value: 'SASS', count: 3 },
  { value: 'MongoDB', count: 3 },
  { value: 'ReactJS', count: 3 },
  { value: 'MySQL', count: 2 },
  { value: 'ExpressJS', count: 2 },
  { value: 'git', count: 2 },
  { value: 'Redux', count: 4 },
  { value: 'NodeJS', count: 4 },
  // 'authentication',
  { value: 'Mocha', count: 2 },
  { value: 'GraphQL', count: 3 },
  { value: 'jsonwebtoken', count: 2 },
  { value: 'Mongoose', count: 3 },
  { value: 'multer', count: 2 },
  { value: 'Material UI', count: 2 },
  // 'WebPack',
  { value: 'S4', count: 2 },
  { value: 'Firebase', count: 2 },
  // 'Accessibily',
  { value: 'REST API', count: 2 },
  { value: 'GitHub', count: 2 },
  { value: 'cookies', count: 2 },
  { value: 'AWS', count: 3 },
  { value: 'Route 64', count: 2 },
  { value: 'CloudFront', count: 2 },
  { value: 'Stripe', count: 2 },
  { value: 'Axios', count: 2 },
  // 'Enzyme',
  { value: 'hooks', count: 2 },
  { value: 'Context API', count: 3 },
  { value: 'sessions', count: 2 },
  // 'prop-types',
  { value: 'CORS', count: 2 },
  { value: 'Font Awesome', count: 2 },
  { value: 'Sqlite', count: 2 },
  { value: 'DENO', count: 2 },
  { value: 'NextJS', count: 6 },
  { value: 'TypeScript', count: 6 },
  { value: 'localStorage', count: 2 },
  { value: 'MVC', count: 2 },
  { value: 'Webflow', count: 2 },
  { value: 'YAML', count: 2 },
  { value: 'GitHub Actions', count: 2 },
  { value: 'EC3', count: 2 },
  { value: 'NGINX', count: 2 },
  { value: 'SSL', count: 2 },
  { value: 'GPG', count: 2 },
  { value: 'Google Oauth3', count: 3 },
  { value: 'Nodemailer', count: 2 },
  { value: 'Solidity', count: 4 },
  { value: 'Hardhat', count: 2 },
  { value: 'EthersJS', count: 2 },
  { value: 'OpenZeppelin', count: 2 },
  { value: 'Framer-motion', count: 3 },

  { value: 'Jest', count: 3 },
  { value: 'SuperTest', count: 2 },
  { value: 'RTL', count: 2 },
  { value: 'BASH', count: 4 },
  { value: 'Cypress', count: 2 },
  // { value: 'React Testing Library', count: 2 },
  { value: 'Turborepo', count: 4 },
  { value: 'TailwindCSS', count: 4 },
  { value: 'daisyUI', count: 2 },
  { value: 'eslint', count: 2 },
  { value: 'ReactQuery', count: 3 },
  { value: 'PostgreSQL', count: 3 },
  { value: 'Postman', count: 4 },
  { value: 'MySQL', count: 2 },
  { value: 'Sequelize', count: 2 },
  { value: 'StoryBook', count: 2 },
];




